parser: babel-eslint
env:
  jest: true
plugins:
  - flowtype
  - prettier
extends:
  - airbnb-base
  - plugin:flowtype/recommended
  - plugin:prettier/recommended
rules:
  comma-dangle:
    - error
    -
      arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  function-paren-newline: off
