parser: babel-eslint
env:
  jest: true
plugins:
  - flowtype
extends:
  - airbnb-base
  - plugin:flowtype/recommended
rules:
  brace-style:
    - 2
    - stroustrup
  comma-dangle:
    - error
    -
      arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  function-paren-newline: off
